#!/usr/bin/env python3
"""
pack_weights_axil.py — Pack the per-block Q8.8 weight hex files into a
single binary image the PS-side bootloader can blast over AXI-Lite at
power-up. Output: weights/db_atcnet.bin + weights/db_atcnet.offsets.h

Each section's BASE_ADDR matches the constants in
ps_demo/db_atcnet_ps_demo.c. Within a section, two consecutive Q8.8
entries are packed into one 32-bit little-endian word:
    word = (entry[i+1] << 16) | entry[i]

To use:
    python3 scripts/pack_weights_axil.py
Then add weights/db_atcnet.bin as a binary asset in the Vitis app.
"""

from __future__ import annotations

import struct
from pathlib import Path

DATA = Path("data/golden_q88")
LUT  = Path("data/lut")
OUT  = Path("weights")

OUT.mkdir(parents=True, exist_ok=True)


def load_q88_hex(path: Path) -> list[int]:
    return [int(line.strip(), 16) for line in path.read_text().splitlines() if line.strip()]


def pack_section(entries: list[int]) -> bytes:
    """Pack a list of 16-bit Q8.8 entries into 32-bit words, little-endian."""
    # Pad to even length.
    if len(entries) % 2:
        entries = entries + [0]
    out = bytearray()
    for i in range(0, len(entries), 2):
        word = (entries[i + 1] << 16) | entries[i]
        out += struct.pack("<I", word & 0xFFFFFFFF)
    return bytes(out)


def main() -> int:
    sections: list[tuple[str, int, Path]] = [
        # (name, base_addr, hex_file)  — base_addr must match ps_demo addresses.
        ("conv2d_w",          0x00000000, DATA / "stage_conv2d_weights.hex"),
        ("conv2d_b",          0x00000800, DATA / "stage_conv2d_bias.hex"),
        ("eca1_w",            0x00000840, DATA / "stage_eca1_weights.hex"),
        ("branchA_dwise_w",   0x00000850, DATA / "stage_branchA_dwise_weights.hex"),
        ("branchA_dwise_b",   0x00000950, DATA / "stage_branchA_dwise_bias.hex"),
        ("branchA_sep_w",     0x00000B50, DATA / "stage_branchA_sep_weights.hex"),
        ("branchA_sep_b",     0x00010B50, DATA / "stage_branchA_sep_bias.hex"),
        ("branchB_dwise_w",   0x00010B58, DATA / "stage_branchB_dwise_weights.hex"),
        ("branchB_dwise_b",   0x00010CD8, DATA / "stage_branchB_dwise_bias.hex"),
        ("branchB_sep_w",     0x00010E58, DATA / "stage_branchB_sep_weights.hex"),
        ("branchB_sep_b",     0x00020E58, DATA / "stage_branchB_sep_bias.hex"),
        ("eca2_w",            0x00020F58, DATA / "stage_eca2_weights.hex"),
        ("chan_d1w_all",      0x00020F70, DATA / "all_chan_d1w.hex"),
        ("chan_d1b_all",      0x00021470, DATA / "all_chan_d1b.hex"),
        ("chan_d2w_all",      0x00021498, DATA / "all_chan_d2w.hex"),
        ("chan_d2b_all",      0x00021998, DATA / "all_chan_d2b.hex"),
        ("spat_conv_w_all",   0x00021A38, DATA / "all_spat_conv_w.hex"),
        ("tcfn_w0_all",       0x00021AD8, DATA / "all_tcfn_w0.hex"),
        ("tcfn_b0_all",       0x00031AE0, DATA / "all_tcfn_b0.hex"),
        ("tcfn_w1_all",       0x00031B00, DATA / "all_tcfn_w1.hex"),
        ("tcfn_b1_all",       0x00041B08, DATA / "all_tcfn_b1.hex"),
        ("tcfn_w2_all",       0x00041B28, DATA / "all_tcfn_w2.hex"),
        ("tcfn_b2_all",       0x00051B30, DATA / "all_tcfn_b2.hex"),
        ("tcfn_w3_all",       0x00051B50, DATA / "all_tcfn_w3.hex"),
        ("tcfn_b3_all",       0x00061B58, DATA / "all_tcfn_b3.hex"),
        ("cls_w_all",         0x00061B78, DATA / "all_cls_w.hex"),
        ("cls_b_all",         0x00061CB8, DATA / "all_cls_b.hex"),
        ("sig_lut",           0x00061CC8, LUT  / "sigmoid_q88.hex"),
        ("elu_lut",           0x000624C8, LUT  / "elu_q88.hex"),
    ]

    image    = bytearray()
    offsets  = []                  # [(name, base, len_words)]
    out_idx  = 0
    print(f"Packing {len(sections)} sections...")
    for name, base, hex_path in sections:
        if not hex_path.exists():
            print(f"  WARN: skipping {name} (missing {hex_path})")
            continue
        entries = load_q88_hex(hex_path)
        packed  = pack_section(entries)
        len_w   = len(packed) // 4
        print(f"  {name:24s} base=0x{base:08x}  entries={len(entries):>6d}  words={len_w:>5d}")
        image += packed
        offsets.append((name, base, len_w))

    bin_path = OUT / "db_atcnet.bin"
    bin_path.write_bytes(bytes(image))
    print(f"\nwrote {bin_path}  ({len(image)} bytes)")

    hdr = ["#pragma once",
           "// Auto-generated by scripts/pack_weights_axil.py.",
           "// Format: { base_addr, word_count } pairs, sentinel { 0xFFFFFFFF, 0xFFFFFFFF }.",
           "static const uint32_t kModelImageOffsets[] = {"]
    for name, base, len_w in offsets:
        hdr.append(f"    0x{base:08x}u, {len_w}u,    // {name}")
    hdr.append("    0xFFFFFFFFu, 0xFFFFFFFFu")
    hdr.append("};")
    hdr_path = OUT / "db_atcnet.offsets.h"
    hdr_path.write_text("\n".join(hdr) + "\n")
    print(f"wrote {hdr_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
