#!/usr/bin/env python3
"""
q88_end_to_end.py — Aggregate per-window classifier logits and produce the
final 1-bit class for HaLT DB-ATCNet, using artifacts already generated by
the per-stage Q8.8 golden scripts.

Inputs (must exist):
    data/golden_q88/stage_w{0..4}_cls_logits.hex   (2 Q8.8 values each)

Outputs:
    data/golden_q88/stage_final_logits_sum.hex     (sum of per-window logits)
    data/golden_q88/stage_final_class.txt          (single integer 0 or 1)

This is a tiny finale that doesn't touch the .h5 — it just verifies the
output of the per-window goldens already present in data/golden_q88/.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np


OUT_DIR    = Path("data/golden_q88")
DATA_WIDTH = 16
N_WIN      = 5
N_CLS      = 2


def load_q88_hex(path: str, shape: tuple) -> np.ndarray:
    flat = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line: continue
            v = int(line, 16)
            if v >= (1 << (DATA_WIDTH - 1)):
                v -= (1 << DATA_WIDTH)
            flat.append(v)
    a = np.array(flat, dtype=np.int32)
    assert a.size == np.prod(shape), f"hex size {a.size} != expected {np.prod(shape)} for {path}"
    return a.reshape(shape)


def to_hex(q: np.ndarray, width: int = 16) -> str:
    mask = (1 << width) - 1
    digits = (width + 3) // 4
    flat = q.flatten()
    return "\n".join(f"{int(v) & mask:0{digits}X}" for v in flat) + "\n"


def main() -> int:
    per_window = []
    for w in range(N_WIN):
        p = OUT_DIR / f"stage_w{w}_cls_logits.hex"
        lg = load_q88_hex(str(p), (N_CLS,))
        per_window.append(lg)
        print(f"window {w}: logits = {lg.tolist()}  argmax = {int(np.argmax(lg))}")
    stacked = np.stack(per_window, axis=0)                          # (5, 2)
    summed  = stacked.sum(axis=0).astype(np.int32)                  # (2,)
    cls     = int(np.argmax(summed))
    print(f"\nsum logits = {summed.tolist()}")
    print(f"final class = {cls}  ({'Right Hand fist' if cls == 0 else 'Left Leg ankle'})")

    # Saturate sum to int16 for the .hex artifact (output of the head module).
    HI = (1 << (DATA_WIDTH - 1)) - 1
    LO = -(1 << (DATA_WIDTH - 1))
    summed_sat = np.clip(summed, LO, HI).astype(np.int16)
    (OUT_DIR / "stage_final_logits_sum.hex").write_text(to_hex(summed_sat, DATA_WIDTH))
    (OUT_DIR / "stage_final_class.txt"    ).write_text(f"{cls}\n")
    (OUT_DIR / "stage_final_meta.json"    ).write_text(json.dumps({
        "per_window_logits": [lg.tolist() for lg in per_window],
        "sum_logits":        summed.tolist(),
        "final_class":       cls,
        "class_label":       "Right Hand fist" if cls == 0 else "Left Leg ankle",
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
