// =============================================================================
// main.c — Zynq UltraScale+ PS (Cortex-A53) bare-metal app for db_atcnet_axi.
//
// Role: bridge ESP32 ↔ NN.
//   1. Receive a 3000-sample EEG window (6000 bytes, 16-bit Q8.8) from the
//      ESP32 over PS UART1.
//   2. DMA the buffer into db_atcnet_axi.s_axis via AXI-DMA MM2S.
//   3. Poll STATUS_REG until the 'done' bit is set.
//   4. Read CLASS_REG (this also clears 'done' in the RTL).
//   5. Send the 1-byte classification back to the ESP32 over UART1.
//   6. Loop.
//
// Debug printf goes via PS UART0 (the on-board USB-UART connector). Status
// updates and any error messages appear in the Vitis terminal at 115200 8N1.
//
// Build:
//   1. Export hardware (.xsa) from Vivado (write_hw_platform -fixed -include_bit).
//   2. In Vitis: New Platform Project from .xsa → standalone (no FreeRTOS).
//   3. New Application Project on that platform → template "Empty Application".
//   4. Drop this file into the application's src/ folder.
//   5. Make sure the BSP exposes XAxiDma + XUartPs drivers (default for ZCU104).
//   6. Build + Run/Debug via JTAG with the bitstream already loaded.
//
// BD prerequisite (one-time setup in the block design):
//   - Enable PS UART1 in the Zynq config (Zynq PS → I/O Configuration → UART 1).
//   - Route UART1 RX/TX via either MIO (if a free MIO is on a header) or EMIO
//     out to a PMOD pin. Connect to ESP32 GPIO17 (TX→RX) / GPIO16 (RX→TX).
// =============================================================================

#include "xparameters.h"
#include "xaxidma.h"
#include "xuartps.h"
#include "xil_io.h"
#include "xil_cache.h"
#include "xil_printf.h"
#include "xstatus.h"
#include <string.h>

// -----------------------------------------------------------------------------
// Configuration
// -----------------------------------------------------------------------------

// db_atcnet_axi AXI-Lite register map (offsets from base; base is in xparameters.h)
#define DBA_BASE_ADDR      0x400000000ULL   // matches the BD's address-editor entry
#define DBA_STATUS_OFFSET  0xF000           // R/O: bit0=busy, bit1=done
#define DBA_CLASS_OFFSET   0xF004           // R/O: bit0=class; reading clears 'done'
#define DBA_STATUS_BUSY    (1U << 0)
#define DBA_STATUS_DONE    (1U << 1)

// EEG window geometry: T_IN=600 timesteps × C_IN=5 electrodes = 3000 samples,
// each 16-bit signed Q8.8.
#define WIN_SAMPLES        3000
#define WIN_BYTES          (WIN_SAMPLES * 2)

// UART1 (to ESP32). 460800 baud must match the ESP32 sketch's UART2_BAUD.
#define ESP_UART_BAUD      460800
#define ESP_UART_DEVICE_ID XPAR_XUARTPS_1_DEVICE_ID    // PS UART1
#define ESP_UART_BASEADDR  XPAR_XUARTPS_1_BASEADDR

// AXI-DMA instance from xparameters.h (auto-generated by Vitis BSP)
#define DMA_DEVICE_ID      XPAR_AXIDMA_0_DEVICE_ID

// Receive-window timeout (ms). If we don't get a full buffer in this time we
// drop it and resync.
#define RX_TIMEOUT_MS      2000

// -----------------------------------------------------------------------------
// Globals
// -----------------------------------------------------------------------------

// DMA source buffer. Aligned to a cache line so cache flushes hit cleanly.
static u8 eeg_buf[WIN_BYTES] __attribute__((aligned(64)));

static XAxiDma  dma;
static XUartPs  esp_uart;

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

static int init_uart_to_esp(void)
{
    XUartPs_Config *cfg = XUartPs_LookupConfig(ESP_UART_DEVICE_ID);
    if (!cfg) {
        xil_printf("[ps] ERROR: XUartPs_LookupConfig(%d) failed\r\n", ESP_UART_DEVICE_ID);
        return XST_FAILURE;
    }
    int status = XUartPs_CfgInitialize(&esp_uart, cfg, cfg->BaseAddress);
    if (status != XST_SUCCESS) return status;

    status = XUartPs_SetBaudRate(&esp_uart, ESP_UART_BAUD);
    if (status != XST_SUCCESS) return status;

    XUartPs_SetOperMode(&esp_uart, XUARTPS_OPER_MODE_NORMAL);
    return XST_SUCCESS;
}

static int init_dma(void)
{
    XAxiDma_Config *cfg = XAxiDma_LookupConfig(DMA_DEVICE_ID);
    if (!cfg) {
        xil_printf("[ps] ERROR: XAxiDma_LookupConfig(%d) failed\r\n", DMA_DEVICE_ID);
        return XST_FAILURE;
    }
    int status = XAxiDma_CfgInitialize(&dma, cfg);
    if (status != XST_SUCCESS) return status;

    if (XAxiDma_HasSg(&dma)) {
        xil_printf("[ps] ERROR: DMA configured with SG; we expect simple-mode\r\n");
        return XST_FAILURE;
    }

    // Disable both DMA interrupts; we're polling.
    XAxiDma_IntrDisable(&dma, XAXIDMA_IRQ_ALL_MASK, XAXIDMA_DEVICE_TO_DMA);
    XAxiDma_IntrDisable(&dma, XAXIDMA_IRQ_ALL_MASK, XAXIDMA_DMA_TO_DEVICE);
    return XST_SUCCESS;
}

// Read 64-bit register from db_atcnet_axi. Vitis provides Xil_In32 for 32-bit
// MMIO; we wrap two reads for the 64-bit address case.
static inline u32 dba_read32(u64 offset)
{
    return Xil_In32((UINTPTR)(DBA_BASE_ADDR + offset));
}

// Lightweight millisecond tick from the Cortex-A53 architectural counter
// (CNTPCT_EL0). Frequency is read once at boot from CNTFRQ_EL0. Avoids the
// extra weight of xtime_l / FreeRTOS tick infrastructure for one-shot timing.
static u64 cntfrq = 0;

static void tick_init(void)
{
    asm volatile ("mrs %0, cntfrq_el0" : "=r"(cntfrq));
}

static u32 tick_ms(void)
{
    u64 v;
    asm volatile ("mrs %0, cntpct_el0" : "=r"(v));
    return (u32)((v * 1000ULL) / cntfrq);
}

// Receive exactly `n` bytes from the ESP32 with a wall-clock timeout (ms).
// Returns the number of bytes actually received (== n on success).
static u32 esp_recv_window(u8 *buf, u32 n, u32 timeout_ms)
{
    u32 got = 0;
    u32 t0  = tick_ms();
    while (got < n) {
        u32 r = XUartPs_Recv(&esp_uart, buf + got, n - got);
        got += r;
        if (tick_ms() - t0 > timeout_ms) break;
    }
    return got;
}

// -----------------------------------------------------------------------------
// Inference cycle
// -----------------------------------------------------------------------------

static int run_one_inference(u8 *out_class)
{
    // 1. Receive window
    u32 got = esp_recv_window(eeg_buf, WIN_BYTES, RX_TIMEOUT_MS);
    if (got != WIN_BYTES) {
        xil_printf("[ps] rx timeout: got %u/%u bytes — dropping\r\n", got, WIN_BYTES);
        return XST_FAILURE;
    }

    // 2. Cache flush so the DMA reads the just-written buffer (Cortex-A53 has
    // a D-cache and the DMA bypasses it via the S_AXI_HP0_FPD port).
    Xil_DCacheFlushRange((UINTPTR)eeg_buf, WIN_BYTES);

    // 3. Kick the DMA MM2S transfer
    int status = XAxiDma_SimpleTransfer(&dma, (UINTPTR)eeg_buf, WIN_BYTES,
                                        XAXIDMA_DMA_TO_DEVICE);
    if (status != XST_SUCCESS) {
        xil_printf("[ps] DMA submit failed: %d\r\n", status);
        return XST_FAILURE;
    }

    // 4. Wait for DMA channel idle (the data has been pushed into the NN)
    while (XAxiDma_Busy(&dma, XAXIDMA_DMA_TO_DEVICE)) { }

    // 5. Poll STATUS_REG for done. Bound the wait so a broken NN doesn't hang
    // the system forever — at ~60 MHz, an inference takes ~510 µs, so even
    // 50 ms of polling is 100× the expected latency.
    u32 deadline_tick = tick_ms() + 50;
    u32 status_reg = 0;
    while (1) {
        status_reg = dba_read32(DBA_STATUS_OFFSET);
        if (status_reg & DBA_STATUS_DONE) break;
        if (tick_ms() > deadline_tick) {
            xil_printf("[ps] NN done-bit never asserted (status=0x%08x)\r\n",
                       (unsigned)status_reg);
            return XST_FAILURE;
        }
    }

    // 6. Read CLASS_REG (this clears 'done' in the RTL)
    u32 cls = dba_read32(DBA_CLASS_OFFSET) & 0x1;
    *out_class = (u8)cls;
    return XST_SUCCESS;
}

// -----------------------------------------------------------------------------
// main
// -----------------------------------------------------------------------------

int main(void)
{
    xil_printf("\r\n=== db_atcnet PS host bring-up ===\r\n");

    Xil_DCacheEnable();
    Xil_ICacheEnable();
    tick_init();

    if (init_uart_to_esp() != XST_SUCCESS) {
        xil_printf("[ps] UART1 init failed\r\n");
        return -1;
    }
    xil_printf("[ps] UART1 to ESP32 @ %d baud\r\n", ESP_UART_BAUD);

    if (init_dma() != XST_SUCCESS) {
        xil_printf("[ps] AXI-DMA init failed\r\n");
        return -1;
    }
    xil_printf("[ps] AXI-DMA ready (MM2S simple mode)\r\n");

    xil_printf("[ps] Waiting for EEG windows from ESP32 (%u bytes each)\r\n",
               (unsigned)WIN_BYTES);

    u32 ok = 0, fail = 0;
    while (1) {
        u8 cls = 0xFF;
        if (run_one_inference(&cls) == XST_SUCCESS) {
            // Send 1-byte classification result back to the ESP32
            XUartPs_Send(&esp_uart, &cls, 1);
            ok++;
            if ((ok & 0xFF) == 0) {
                xil_printf("[ps] OK total=%u  fail=%u  last_class=%u\r\n",
                           (unsigned)ok, (unsigned)fail, (unsigned)cls);
            }
        } else {
            fail++;
            // Don't send anything on failure; ESP32 watchdog will drive
            // motors to rest on its own.
        }
    }
    // unreachable
}
